### ISSUE TITLE
ModuleNotFoundError: No module named 'pubsub'

### ISSUE THREAD

**Issue by weishuhn** [canvas-medical/canvas-plugins#144]
I'm not sure if you're ready for outside feedback but I was playing around with this a bit.  

After installing the `canvas` library I created a plugin using `canvas init  [PLUGIN_NAME]` and then I ran `canvas validate-manifest [PLUGIN_NAME]`.  

I ended up with the following error:

![image](https://github.com/user-attachments/assets/51ed246a-9812-49b6-96a0-9a9792a152f2)

From what I can tell, I think the local `pubsub` package needs to be added to the `pyproject.toml` file but I'm new to poetry and so could be wrong. 

https://github.com/canvas-medical/canvas-plugins/blob/2d2352d7354599a6bad15a7820a8c1d217144a6a/pyproject.toml#L42-L43

I'm using the latest CLI version: `canvas_cli Version: 0.2.11`

**Comment by aduane** [comment]
Hey there, thanks for the report!

We fixed this in https://github.com/canvas-medical/canvas-plugins/pull/140, but we haven't cut a new release/published to pypi just yet. I would expect that to happen sometime this week.

**Comment by aduane** [comment]
You are correct that including pubsub in the `pyproject.toml` would fix the issue, we instead took a different route. The code was loading the plugin classes to pull some of the Meta class attributes from them. Instead of loading the plugin classes (which would require all modules that class imported to be shipped with the CLI), we chose to use the [python AST module](https://docs.python.org/3/library/ast.html) to parse the classes and retrieve that class metadata.
